name = "morphic"
type = "javascript" # or "webpack" if using a bundler
account_id = "3f26164df851b3218de5a3da200aa8f5"
workers_dev = true
compatibility_date = "2024-09-21"

[env.production]
workers_dev = false
